### ISSUE TITLE
feat, error : 다크모드 구현 중 hydration 에러

### ISSUE THREAD

**Issue by dv-yeop920** [Five-Rookies/final-project#38]
### 주요 기능
버튼 누르면 다크모드 라이트 모드 전환

### 진행 사항
- [x] zustand store 생성 persist 까지 생성
- [x] 상태에 따라 scss 컬러 적용 하기

### 이슈 (있으면 작성)
Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering. 에러
-원인 ssr + persist 미들웨어 사용시 UI 미스매치
-다크모드 실행시  store hydrate당시 store의 상태와, 서버에서 문서가 만들어질때의 store의 상태가 달라서 다른 컨텐츠가 그려졌기 때문에 생기는 문제

**Comment by jeonbar2** [comment]
에러 기능 좋아요

**Comment by jeonbar2** [comment]
이슈기능 라벨 바꿔서 써주세요
